### PR TITLE
Fix "Connectors are lost when opened in Editor"

### LINKED ISSUE #79: Connectors are lost when opened in Editor
I have this defined in Azure

    "$connections": {
        "value": {
            "dynamicsax": {
                "connectionId": "/subscriptions/[my_subscription]/resourceGroups/[my_resource_group]/providers/Microsoft.Web/connections/dynamicsax",
                "connectionName": "dynamicsax",
                "id": "/subscriptions/[my_subscription]/providers/Microsoft.Web/locations/westeurope/managedApis/dynamicsax"
            },
            "sql": {
                "connectionId": "/subscriptions/[my_subscription]/resourceGroups/[my_resource_group]/providers/Microsoft.Web/connections/sql-1",
                "connectionName": "sql",
                "id": "/subscriptions/[my_subscription]/providers/Microsoft.Web/locations/westeurope/managedApis/sql"
            }
        }
    }

and this is what I see in VS Code, when opened in Editor

    "parameters": {
        "$connections": {
            "defaultValue": {},
            "type": "Object"
        }
    },

When I update Azure, the Logic Apps fail to run, because the Connectors are overwritten.

### PR DESCRIPTION
**Pull request by joechung-msft**
- Fix #79

### CODE REVIEW

File: src/tree/logic-app/LogicAppTreeItem.ts [hunk 1]
```diff
@@ -119,10 +119,8 @@ export class LogicAppTreeItem implements IAzureParentTreeItem {
 
     public async update(definition: string): Promise<string> {
         const workflow: Workflow = {
-            definition: JSON.parse(definition),
-            integrationAccount: this.workflow.integrationAccount || undefined,
-            location: this.workflow.location,
-            tags: this.workflow.tags || undefined
+            ...this.workflow,
```
Comment (joechung-msft) [inline src/tree/logic-app/LogicAppTreeItem.ts]: Include all workflow properties from previous version, not just `integrationAccount`, `location`, and `tags`.
